# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_gene_expression_level <- function(counts, cell_size, vmin, vmax, numbin, a, b) {
    .Call(`_SanityR_get_gene_expression_level`, counts, cell_size, vmin, vmax, numbin, a, b)
}

